### ISSUE TITLE
Indexing to place branch lengths

### ISSUE THREAD

**Issue by duchene** [revbayes/revbayes.archive#90]
I would like to monitor the rate estimates for specific branches. One way to do this is to use the treeAssembly() function and monitor the tree with the rates as branch lengths. But it seems like treeAssembly() only takes topology objects from dnUniformTopology().

Another way to do this is to know the indexing method that RevBayes uses to place branch lengths from a given vector, and then I could write a function in R to use the monitored rates as branch lengths.

Any help with this would be greatly appreciated.

**Comment by duchene** [comment]
Hi Sebastian,

Thanks for your help, "mvExtNewick" works perfectly.

I am analysing simulated data with a known matrix of substitutions. Is
there a way to fix the value of the Q matrix to make my runs faster?
Functions that produce rateMatrix objects, like "fnGTR", only accept the
output of distribution functions, like "dnDirichlet", but there must be a
way to get around this and set an arbitrary value for Q.

Thanks a lot for helping me with these couple of issues.

Cheers,

David Duchene

**Comment by hoehna** [comment]
Hi David,

I saw that you solved the problem yourself now. In general, it should be
possible to use any stochastic variable also as a constant variable.
Important is the assignment operator '<-' and the function to create the
variable, such as simplex.
It should be faster for your simulations, but maybe not by much. Actually,
it is only faster if in the previous analyses you estimated the
substitution rate parameters as well.

Let me know if you have any other questions.


Best,
Sebastian
